### ISSUE TITLE
Unknown Prop Warning in react 15.2.0

### ISSUE THREAD

**Issue by twisty** [twisty/formsy-react-components#80]
Because we pass all props on to the form control, we're getting "unknown prop" warnings springing up all over the place when using `react 15.2.0`.

https://facebook.github.io/react/warnings/unknown-prop.html

This will be fixed in due course. If the warnings hurt your eyes, you could:

* just try and ignore them 😄 
* remain on `react 15.1`
* [filter them out](https://github.com/react-bootstrap/react-bootstrap/issues/1994#issuecomment-230367989)

Note: these are just warnings, they don't show in production mode, and the library works just the same as it did before.

**Comment by Semigradsky** [comment]
@twisty [This code](https://github.com/christianalfoni/formsy-react/blob/6b167cbfe15a72430ff475a92a70273e67a663f5/src/main.js#L426-L440) removed warnings for `formsy-react`. You can do the same.

**Comment by twisty** [comment]
Fixed in 1b4423036aaed27d4ea9702bcfab568f6cfe907e

**Comment by twisty** [comment]
([Reported here first](https://github.com/christianalfoni/formsy-react/issues/363))

**Comment by martinhbramwell** [comment]
I have upgraded to formsy-react 0.8.1 but still see 1 of the 2 warning I saw earlier : 

     modules.js?hash=b518095…:37536 Warning: Unknown props `onValidSubmit`, `onSubmitted` on <form> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
         in form (created by Formsy)
         in Formsy (created by _form)


Here's the code ( _form.jsx ) I'm working with : 

    import React from 'react';

    import Formsy from 'formsy-react';
    import {
      // Checkbox,
      // CheckboxGroup,
      Input,
      // RadioGroup,
      Row,
      // Select,
      // File,
      // Textarea

    } from 'formsy-react-components';

    export default React.createClass({


      resetForm() {
        // console.log('resetForm');
        this.refs.form.reset();
      },

      validSubmit(data) {
        // console.log('validSubmit', data);
        this.props.submitAction(data.email, data.password);
      },

      // invalidSubmit(data) {
      invalidSubmit() {
        // console.log('invalidSubmit', data);
      },

      enableButton() {
        // console.log('enable button');
        this.setState({ canSubmit: true });
      },

      disableButton() {
        // console.log('disable button');
        this.setState({ canSubmit: false });
      },

      getInitialState() {
        return {
          layout: 'vertical',
          validatePristine: true,
          disabled: false,
          canSubmit: false
        };
      },

      render() {

        let formClassName = 'vertical m-t';

        var sharedProps = {
          layout: this.state.layout,
          validatePristine: this.state.validatePristine,
          disabled: this.state.disabled
        };

        const {exception} = this.props;

        return (

            <Formsy.Form className={formClassName}
              onValidSubmit={this.validSubmit}
              onInvalidSubmit={this.invalidSubmit}
              onValid={this.enableButton}
              onInvalid={this.disableButton}
              onChange={this.onChange}
              ref="form">

              <fieldset>
                {exception ?
                <div data-cuke="bad-mailing" className="alert alert-danger" onClick="">
                  <span className="unicon fatal icon-white icon-24" ></span>
                  {exception}
                </div> : null }
                <Input
                    {...sharedProps}
                    name="email"
                    value=""
                    label="Email"
                    type="email"
                    placeholder="This is an email input."

                    data-cuke='rst-email'

                    autoComplete="off"

                    validations="isEmail"
                    validationError="Please provide a valid email address."

                />

              </fieldset>

              <Row layout={this.state.layout}>

                <input className="btn btn-primary block full-width m-b"
                  formNoValidate={true}
                  disabled={!this.state.canSubmit}

                  data-cuke='submit-rst-email'

                  type="submit"
                  defaultValue="Send new password" />

              </Row>

            </Formsy.Form>

        );
      }
    });

**Comment by twisty** [comment]
Hi there @martinhbramwell -- Those two warnings should have been fixed in the latest release of `formsy-react` (according to the [release notes](https://github.com/christianalfoni/formsy-react/releases/tag/v0.18.1)).

Are you sure you're up-top-date on that dependency?

**Comment by martinhbramwell** [comment]
You're correct.  I only updated `formsy-react-components`.

**Comment by afgarcia86** [comment]
I don't believe this fix has been applied to the bootsrap-v4 branch 🙈

**Comment by junibrosas** [comment]
I still have issues with the form with the recent update, react 0.15 and formsy 0.18.

Unknown prop `layout` on <form> tag.

**Comment by afgarcia86** [comment]
@junibrosas if you use my branch I ported over the required changes. Still waiting for my pull request to get accepted. https://github.com/afgarcia86/formsy-react-components

**Comment by junibrosas** [comment]
@afgarcia86 , I will use your branch. I will check to see if it is working. Thanks!
