### ISSUE TITLE
React.createElement: Type is invalid when creating a Form

### ISSUE THREAD

**Issue by carlos-sarmiento** [twisty/formsy-react-components#93]
I'm trying to use Formsy in a project and Chrome is throwing the following error at me:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components)
or a class/function (for composite components) but got: object. Check the render method 
of `SubscriptionAddPanelBase`.
```

I'm importing formsy-react-components with this:
```
import { Form } from "formsy-react-components";
```

This is the render method for SubscriptionAddPanelBase:
```
render() {
    return
        (<div>
            <Form />
        </div>);
}
```

If I remove the `<Form />` from there, everything works correctly.

Also, if instead of importing `formsy-react-components` I import `formsy-react`, the code works and no error is thrown.

**Comment by twisty** [comment]
Good catch. I've just released v0.10.0 which should fix for this.

**Comment by carlos-sarmiento** [comment]
Seems to be fixed in v.0.10.0

**Comment by vincro** [comment]
Using the standard example reproduces the same error still in version 0.11.1
